### ISSUE TITLE
StencilSwiftKit filters don’t work

### ISSUE THREAD

**Issue by komaji** [yhkaplan/scaffold#1]
When I try using the filter added by StencilSwiftKit, I get the following error:
`Error: Unknown filter'lowerFirstWord'. A similar filter was found:'lowercase'.`

**Comment by yhkaplan** [comment]
It might be a newer feature of stencilkit so I'll test it on the updated branch first

**Comment by yhkaplan** [comment]
Looks like using this code as an example will fix it. I ought to add developer docs to StencilKit so it's more obvious how to use.

https://github.com/SwiftGen/SwiftGen/blob/5e89523596fd3043b1d4031a8a3e5992fcce7ea3/Sources/SwiftGen/Config/Config%2BRun.swift#L63-L72

**Comment by komaji** [comment]
Wroks fine on `add-context-file-flag` branch 😄
